'use client';

import { useState } from 'react';
import { ChevronDownIcon } from '@heroicons/react/24/outline';

/**
 * Quick FAQ Component
 * 
 * Addresses common objections and questions above the fold
 * to reduce conversion friction
 */

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: 'How does MediaPlanPro help my business grow?',
    answer: 'MediaPlanPro provides a complete marketing ecosystem: AI-powered strategy builder, 30+ professional tools, expert insights through our blog, and optional professional services. Start with the Strategy Builder, explore our tools, learn from expert content, and scale with our services when ready.',
  },
  {
    question: 'What tools and resources are available?',
    answer: 'Access 30+ professional marketing tools including SEO analyzers, content generators, social media planners, and ROI calculators. Plus, get expert insights from our blog with actionable strategies, industry trends, and proven tactics. Everything you need to execute your marketing strategy effectively.',
  },
  {
    question: 'How do I get started?',
    answer: 'Start by building your marketing strategy with our AI-powered Strategy Builder (takes 60 seconds). Then explore our professional tools to execute your strategy. Read our blog for expert insights and best practices. When you need hands-on help, our professional services are available.',
  },
  {
    question: 'Can I see examples before getting started?',
    answer: 'Absolutely! Click "See Sample Plan" to view a real marketing strategy generated by our AI. Browse our blog for case studies and expert insights. Explore our tools section to see what\'s available. No signup required to get started.',
  },
];

export function QuickFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-16 bg-white dark:bg-bg-primary">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Heading */}
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-medium text-gray-900 dark:text-text-primary mb-4">
            Common Questions
          </h2>
          <p className="text-lg text-gray-600 dark:text-text-secondary">
            Everything you need to know before getting started
          </p>
        </div>

        {/* FAQ List */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-gray-50 dark:bg-bg-secondary border border-gray-200 dark:border-border-primary rounded-lg overflow-hidden transition-all duration-300 hover:border-blue-500/30 dark:hover:border-[#F59E0B]/30"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-4 flex items-center justify-between text-left transition-colors duration-200 hover:bg-gray-100 dark:hover:bg-bg-tertiary"
              >
                <span className="text-lg font-medium text-gray-900 dark:text-text-primary pr-4">
                  {faq.question}
                </span>
                <ChevronDownIcon
                  className={`h-5 w-5 text-gray-600 dark:text-text-secondary flex-shrink-0 transition-transform duration-300 ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                />
              </button>

              {/* Answer */}
              <div
                className={`overflow-hidden transition-all duration-300 ${
                  openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                }`}
              >
                <div className="px-6 pb-4 text-gray-600 dark:text-text-secondary leading-relaxed">
                  {faq.answer}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="mt-8 text-center">
          <p className="text-sm text-gray-500 dark:text-text-tertiary">
            Still have questions?{' '}
            <a href="/contact" className="text-blue-600 dark:text-[#F59E0B] hover:underline">
              Contact our team
            </a>
          </p>
        </div>
      </div>
    </section>
  );
}

